// Generated by CoffeeScript 1.8.0
(function() {
  var gui, isDebug, path, win;

  isDebug = true;

  gui = require('nw.gui');

  path = require('path');

  win = gui.Window.get();

  win.title = gui.App.manifest.name + ' ' + gui.App.manifest.version;

  win.focus();

  win.show();

  win.on("new-win-policy", function(frame, url, policy) {
    return policy.ignore();
  });

}).call(this);
