serverInfo:
 port: 443
 staticDir: static
 threads: 0
 #lockDir: "/var/lock/"
 #remoteAdminPass: password
redisInfo:
 connection:
  host: "127.0.0.1"
  port: 6379
  #password: null
 cacheExpire: 300
external:
 redis: "redis-server"
 ffmpeg: ffmpeg
 ffprobe: ffprobe
dirs:
 configDir: "/etc/video-sync"
 encodeDir: "/var/video-sync/encode"
 mediaDir: "/var/video-sync/media"
 serverLogDir: "/var/log/video-sync/server"
 encodeLogDir: "/var/log/video-sync/encoding"
ffmpeg:
 codecs: "(mov|mp4|webm|mkv|avi)"
 ffprobe: "-v quiet -show_streams -print_format json {}"
 templates:
  default:
   webm:
    video:
     1280x720_: "-y -i {} -c:v libvpx-vp9 -s 1280x720 -b:v 800k -keyint_min 75 -g 75 -threads 4 -speed 2 -tile-columns 4 -frame-parallel 1 -an -sn -f webm -dash 1 -pass 1 /dev/null"
     1280x720: "-y -i {} -c:v libvpx-vp9 -s 1280x720 -b:v 800k -keyint_min 75 -g 75 -threads 4 -speed 2 -tile-columns 4 -frame-parallel 1 -an -sn -f webm -dash 1 -pass 2 {}"
    audio:
     256k: "-y -i {} -vn -sn -c:a libvorbis -b:a 256k -f webm -dash 1 {}"
    subtitle: "-y -txt_format text -i {} {}"
    manifest:
     base: "-y {} -c copy {} -f webm_dash_manifest -adaptation_sets \"id=0,streams={} id=1,streams={}\" {}"
     input: "-f webm_dash_manifest -i {}"
     map: "-map {}"
ssl:
 selfSign: true
 key: "/etc/video-sync/certificate.key"
 crt: "/etc/video-sync/certificate.crt"
log:
 #logEncoding: true
 levels:
  ADMINISTRATION: debug
  AUTHENTICATION: debug
  DATABASE: debug
  ENCODING: debug
  GENERAL: debug
  LOG: debug
  STATE: debug
  VIDEO: debug
  UTILS: debug
